let mime = {
    apk: ["apk"],
    assembly: ["class"],
    audio: ["mp3", "au", "aif", "aifc", "wav"],
    css: ["css"],
    database: ["db"],
    document: ["txt"],
    excel: ["xls", "xla", "xlsx"],
    exe: ["exe"],
    html: ["html", "htm", "stm"],
    ico: ["ico"],
    image: ["bmp", "jpe", "jpeg", "jpg", "svg", "png", ""],
    ipa: ["ipa"],
    iso: ["iso"],
    java: ["java"],
    javascript: ["js"],
    json: ["json"],
    markdown: ["md"],
    pdf: ["pdf"],
    ppt: ["ppt", "pot", "pps"],
    python: ["py"],
    shell: ["sh"],
    url: ["url"],
    word: ["doc", "docx", "dot"],
    zip: ["rar", "7z", "zip", "gz"],
    setting: ["conf"],
    folder: ["folder"]
};

export default mime;